# bermanpunahou/slugs/main/smiley-more

check50:
  checks:
    srb:
      - run: "./colorize smiley.bmp outfile.bmp"
        exit: 0

submit50:
  files:
    - !include "helpers.c"
    - !exclude "helpers"
