# bermanpunahou/slugs/main/smiley-more

submit50:
  files:
    - !include "helpers.c"
    - !exclude "bmp.h"
    - !exclude "colorize"
    - !exclude "colorize.c"
    - !exclude "helpers.h"
    - !exclude "helpers-orig.c"
    - !exclude "Makefile"
    - !exclude "outfile.bmp"
    - !exclude "smiley.bmp"
