# check50 bermanpunahou/slugs/main/hours

check50:
  checks:
      hello world:
        - run: ./hello
          stdout: Hello, world!\n
          exit: 0
      foo:
        - run: ./hello
          stdout: bar
          exit: 0
  files:
    - !require "hello.c"
