# slug: bermanpunahou/slugs/main/initials

check50:
  checks:
    srb:
      - run: ./initials Samantha Ruth Berman
        stdout: SRB
        exit: 0
    

submit50:
  files:
    - !include "initials.c"
      
