# check50 bermanpunahou/slugs/main/initials

check50:
  checks:
      hello world:
        - run: ./initials
          stdout: Hello, world!\n
          exit: 0
          
submit50:
  files:
    - !include "initials.c"
