# check50 bermanpunahou/slugs/main/initials

check50:
  checks:
    srb:
      - run: ./initials Samantha Ruth Berman
        stdout: S.R.B.\n
        exit: 0
    eab:
      - run: ./initials Emily Ayelet Berman
        stdout: E.A.B.\n
        exit: 0
    emily:
      - run: ./initials Emily
        stdout: "correct usage: ./initials [your full name]\n"
        exit: 1
    empty:
      - run: ./initials
        stdout: "correct usage: ./initials [your full name]\n"
        exit: 1

submit50:
  files:
    - !include "initials.c"
    - !exclude "initials"
