# check50 bermanpunahou/slugs/main/initials

check50:
  checks:
    empty:
      - run: ./initials
        stdout: correct usage: ./initials [your full name]
        exit: 1

submit50:
  files:
    - !include "initials.c"
